import { motion } from "framer-motion";
import Head from "next/head";
import { Header } from "src/component/Header";
import { Footer } from "src/component/Footer";
import { AboutHead } from "src/component/AboutPage/AboutHead";
import { AboutMain } from "src/component/AboutPage/AboutMain";

const About = () => {
  return (
    <motion.div
      initial={{ opacity: 0 }} // 初期状態
      animate={{ opacity: 1 }} // マウント時
      exit={{ opacity: 0 }} // アンマウント時
    >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <AboutHead />
      <AboutMain />
      <Footer />
    </motion.div>
  );
};
export default About;
