import Head from "next/head";
import { Header } from "src/component/Header";
import { Footer } from "src/component/Footer";
import { AboutHead } from "src/component/AboutPage/AboutHead";
import { AboutMain } from "src/component/AboutPage/AboutMain";

const About = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <AboutHead />
      <AboutMain />
      <Footer />
    </div>
  );
};
export default About;
