import { motion } from "framer-motion";
import Head from "next/head";
import { client } from "src/libs/client";
import { Header } from "src/component/Header";
import { WorksPosts } from "src/component/WorksPage/WorksPosts";
import { Footer } from "src/component/Footer";
import { WorksHead } from "src/component/WorksPage/WorksHead";

const Works = (props) => {
  return (
    <motion.div
      initial={{ opacity: 0 }} // 初期状態
      animate={{ opacity: 1 }} // マウント時
      exit={{ opacity: 0 }} // アンマウント時
    >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <WorksHead />
      <WorksPosts props={props} />
      <Footer />
    </motion.div>
  );
};
export const getStaticProps = async () => {
  const data = await client.getList({ endpoint: "works" });
  return {
    props: data,
  };
};

export default Works;
