import Head from "next/head";
import { motion } from "framer-motion";
import { About } from "src/component/About";
import { Feature } from "src/component/Feature";
import { Footer } from "src/component/Footer";
import { Header } from "src/component/Header";
import { Mv } from "src/component/Mv";

const Home = () => {
  return (
    <motion.div
      initial={{ opacity: 1 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0, x: -500 }}
      transition={{ ease: "easeInOut", duration: 0.5 }}
    >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Mv />
      <Feature />
      <About />
      <Footer />
    </motion.div>
  );
};
export default Home;
