import Head from "next/head";
import { About } from "src/component/About";
import { Feature } from "src/component/Feature";
import { Footer } from "src/component/Footer";
import { Header } from "src/component/Header";
import { Mv } from "src/component/Mv";
import { Works } from "src/component/Works";
import { client } from "src/libs/client";
import Link from "next/link";
import { useCallback } from "react";

const Home = (props) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Mv />
      <Feature />
      <About />
      <Works props={props} />
      <Footer />
    </div>
  );
};
export const getStaticProps = async () => {
  const data = await client.getList({ endpoint: "works" });
  return {
    props: data,
  };
};

export default Home;
